version: "3.9"

services:
  study_view:
    image: study_view:dev        # ğŸ‘ˆ æ˜ç¡®ç»™å¼€å‘é•œåƒå‘½å
    build: .
    container_name: view_dev

    ports:
      - "5000:5000"

    volumes:
      # ğŸ”¥ ä»£ç å®æ—¶åŒæ­¥ï¼ˆå¼€å‘æ ¸å¿ƒï¼‰
      - .:/app

    environment:
      - FLASK_ENV=development
      - STUDY_ADMIN_USER=my_custom_admin
      - STUDY_ADMIN_PASS=secret_password_2024
      - FLASK_SECRET_KEY=anything_unique_string
    restart: unless-stopped
